# -*- coding: utf-8 -*-
"""FunFacts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tyKouWXgIln7WU-lkhLfu6sLVrsumCIc
"""

import streamlit as st

st.set_page_config(page_title="Fun Facts", page_icon="🌱")

st.markdown("""
<style>
.card {
    background: #1b1f27;
    padding: 18px;
    border-radius: 12px;
    margin-bottom: 12px;
    box-shadow: 0 0 18px rgba(0,255,200,0.1);
}
.label {
    font-size: 20px;
    font-weight: 700;
    color: #86e1ff;
}
.fact {
    font-size: 15px;
    margin-top: 6px;
    color: #d4d4d4;
}
</style>
""", unsafe_allow_html=True)


st.title("Plant Disease Fun Facts")
st.write("Fakta menarik berdasarkan *38 class* yang dipakai model DenseNet lo.")

FUN_FACTS = {
    "Apple___Apple_scab": "Apple scab disebabkan jamur Venturia — bisa bikin apel tampak berkarat.",
    "Apple___Black_rot": "Black rot juga bisa menyerang ranting, bukan cuma buah atau daun.",
    "Apple___Cedar_apple_rust": "Penyakit ini butuh pohon cedar & apple untuk siklus hidupnya.",
    "Apple___healthy": "Daun apel yang sehat biasanya punya warna hijau tajam tanpa bintik.",
    "Blueberry___healthy": "Blueberry sehat kuat terhadap jamur kalau kelembabannya stabil.",
    "Cherry_(including_sour)___Powdery_mildew": "Powdery mildew suka kondisi kering — jarang muncul saat hujan terus menerus.",
    "Cherry_(including_sour)___healthy": "Daun cherry sehat punya pinggiran yang halus dan mengkilap.",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Gray leaf spot bisa turunkan hasil jagung sampai 50%.",
    "Corn_(maize)___Common_rust_": "Common rust jagung lebih sering muncul saat suhu dingin & lembab.",
    "Corn_(maize)___Northern_Leaf_Blight": "Northern leaf blight punya gejala oval panjang yang khas.",
    "Corn_(maize)___healthy": "Jagung sehat tumbuh pesat dengan sinar matahari penuh.",
    "Grape___Black_rot": "Black rot anggur muncul dari hujan awal musim semi.",
    "Grape___Esca_(Black_Measles)": "Esca bisa buat bercak 'mata' gelap di permukaan anggur.",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Isariopsis menyebabkan pola bercak berbentuk sudut.",
    "Grape___healthy": "Anggur sehat biasanya punya daun besar dan tebal.",
    "Orange___Haunglongbing_(Citrus_greening)": "HLB adalah penyakit paling mematikan jeruk dunia.",
    "Peach___Bacterial_spot": "Bacterial spot bikin 'shot holes' kecil di daun peach.",
    "Peach___healthy": "Daun peach sehat halus dan sedikit berbulu.",
    "Pepper,_bell___Bacterial_spot": "Bacterial spot paprika sering muncul setelah hujan deras.",
    "Pepper,_bell___healthy": "Paprika sehat punya daun tebal tanpa kerutan.",
    "Potato___Early_blight": "Early blight bikin pola 'target' melingkar yang khas.",
    "Potato___Late_blight": "Late blight penyebab kelaparan besar Irlandia tahun 1840-an.",
    "Potato___healthy": "Daun kentang sehat punya bentuk oval besar.",
    "Raspberry___healthy": "Daun raspberry sehat bertekstur berkerut alami.",
    "Soybean___healthy": "Kedelai sehat biasanya tumbuh simetris di tiap node.",
    "Squash___Powdery_mildew": "Squash gampang kena powdery mildew saat kurang sinar matahari.",
    "Strawberry___Leaf_scorch": "Leaf scorch tidak menyerang buah strawberry, hanya daun.",
    "Strawberry___healthy": "Strawberry sehat punya daun mengkilap dengan tiga lobus.",
    "Tomato___Bacterial_spot": "Bacterial spot tomat bisa menyebar lewat percikan air hujan.",
    "Tomato___Early_blight": "Early blight bikin pola cincin 'bullseye' di daun tomat.",
    "Tomato___Late_blight": "Late blight adalah penyakit yang merusak tomat paling cepat.",
    "Tomato___Leaf_Mold": "Leaf mold tumbuh cepat di greenhouse yang lembab.",
    "Tomato___Septoria_leaf_spot": "Septoria membuat titik-titik kecil seragam di daun tomat.",
    "Tomato___Spider_mites Two-spotted_spider_mite": "Spider mites suka kondisi panas dan kering ekstrem.",
    "Tomato___Target_Spot": "Target spot sering muncul pada tomat saat musim hujan.",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "TYLCV disebarkan oleh kutu kebul (whiteflies).",
    "Tomato___Tomato_mosaic_virus": "TMV bisa bertahan di tanah lebih dari 50 tahun.",
    "Tomato___healthy": "Tomat sehat cenderung berbau khas ketika diremas sedikit."
}

# === Auto-generate cards ===
for cls, fact in FUN_FACTS.items():
    pretty = cls.replace("___", " — ").replace("_", " ")
    st.markdown(f"""
    <div class='card'>
        <div class='label'>{pretty}</div>
        <div class='fact'>{fact}</div>
    </div>
    """, unsafe_allow_html=True)
