# -*- coding: utf-8 -*-
"""FunFacts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tyKouWXgIln7WU-lkhLfu6sLVrsumCIc
"""

import streamlit as st

st.set_page_config(page_title="Fun Facts", page_icon="🌱")

st.markdown("""
<style>
.card {
    background: #1b1f27;
    padding: 18px;
    border-radius: 12px;
    margin-bottom: 12px;
    box-shadow: 0 0 18px rgba(0,255,200,0.1);
}
.label {
    font-size: 20px;
    font-weight: 700;
    color: #86e1ff;
}
.fact {
    font-size: 15px;
    margin-top: 6px;
    color: #d4d4d4;
}
</style>
""", unsafe_allow_html=True)


st.title("Plant Disease Fun Facts")
st.write("Fakta menarik berdasarkan *38 class* yang dipakai model DenseNet lo.")

FUN_FACTS = {
    "Apple___Apple_scab": "Apple scab disebabkan oleh jamur Venturia inaequalis, yang menimbulkan bercak berwarna gelap menyerupai karat pada permukaan daun dan buah.",
    "Apple___Black_rot": "Black rot tidak hanya menyerang buah dan daun, tetapi juga dapat menginfeksi ranting dan batang pohon apel.",
    "Apple___Cedar_apple_rust": "Cedar apple rust membutuhkan dua inang dalam siklus hidupnya, yaitu pohon cedar dan pohon apel.",
    "Apple___healthy": "Daun apel yang sehat memiliki warna hijau cerah dan bebas dari bercak maupun perubahan tekstur.",
    "Blueberry___healthy": "Tanaman blueberry yang sehat umumnya lebih tahan terhadap infeksi jamur selama kelembapan terjaga stabil.",
    "Cherry_(including_sour)___Powdery_mildew": "Powdery mildew pada cherry lebih sering berkembang pada kondisi kering dengan sirkulasi udara terbatas.",
    "Cherry_(including_sour)___healthy": "Daun cherry sehat ditandai dengan permukaan mengilap dan tepi daun yang halus.",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Gray leaf spot dapat menurunkan hasil panen jagung hingga 50% jika tidak dikelola dengan baik.",
    "Corn_(maize)___Common_rust_": "Common rust pada jagung berkembang optimal dalam kondisi udara lembap dan suhu yang lebih dingin.",
    "Corn_(maize)___Northern_Leaf_Blight": "Northern leaf blight memiliki gejala khas berupa bercak panjang berbentuk elips pada daun.",
    "Corn_(maize)___healthy": "Jagung yang sehat tumbuh optimal di bawah sinar matahari penuh dan tanah yang kaya nutrisi.",
    "Grape___Black_rot": "Infeksi black rot pada anggur biasanya dimulai pada awal musim semi akibat percikan air hujan.",
    "Grape___Esca_(Black_Measles)": "Penyakit Esca dapat menghasilkan bercak gelap menyerupai 'mata' pada permukaan buah anggur.",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Isariopsis leaf spot menyebabkan bercak berbentuk sudut yang mengikuti pola urat daun.",
    "Grape___healthy": "Daun anggur sehat umumnya berukuran besar, tebal, dan tidak menunjukkan tanda perubahan warna.",
    "Orange___Haunglongbing_(Citrus_greening)": "Citrus greening (HLB) merupakan salah satu penyakit paling merusak pada tanaman jeruk di seluruh dunia.",
    "Peach___Bacterial_spot": "Bacterial spot pada peach dapat menimbulkan lubang kecil pada daun yang dikenal dengan istilah ‘shot holes’.",
    "Peach___healthy": "Daun peach yang sehat memiliki tekstur halus dan permukaan sedikit berbulu.",
    "Pepper,_bell___Bacterial_spot": "Bacterial spot pada paprika sering berkembang setelah periode hujan atau kelembapan tinggi.",
    "Pepper,_bell___healthy": "Daun paprika sehat cenderung bertekstur tebal dan tidak memiliki kerutan atau bercak.",
    "Potato___Early_blight": "Early blight memiliki pola melingkar yang khas, menyerupai target atau cincin konsentris.",
    "Potato___Late_blight": "Late blight adalah penyakit yang menyebabkan kegagalan panen besar pada Irlandia pada tahun 1840-an.",
    "Potato___healthy": "Daun kentang yang sehat memiliki bentuk oval dan tekstur yang utuh.",
    "Raspberry___healthy": "Daun raspberry sehat biasanya memiliki tekstur berkerut alami dengan warna hijau merata.",
    "Soybean___healthy": "Tanaman kedelai sehat memperlihatkan pertumbuhan simetris dan warna daun yang seragam.",
    "Squash___Powdery_mildew": "Powdery mildew pada squash lebih mudah berkembang pada kondisi minim cahaya matahari dan sirkulasi udara terbatas.",
    "Strawberry___Leaf_scorch": "Leaf scorch hanya menyerang daun strawberry dan tidak menginfeksi buah.",
    "Strawberry___healthy": "Daun strawberry sehat mengilap dan memiliki tiga lobus yang seragam.",
    "Tomato___Bacterial_spot": "Bacterial spot pada tomat dapat menyebar melalui percikan air hujan atau irigasi.",
    "Tomato___Early_blight": "Early blight menimbulkan bercak berbentuk cincin konsentris yang mirip 'bullseye'.",
    "Tomato___Late_blight": "Late blight merupakan salah satu penyakit paling agresif yang menyerang tanaman tomat.",
    "Tomato___Leaf_Mold": "Leaf mold berkembang pesat pada lingkungan greenhouse yang lembap dan kurang ventilasi.",
    "Tomato___Septoria_leaf_spot": "Septoria leaf spot menghasilkan banyak titik kecil seragam yang tersebar di seluruh permukaan daun.",
    "Tomato___Spider_mites Two-spotted_spider_mite": "Serangan spider mites meningkat pada kondisi cuaca panas dan sangat kering.",
    "Tomato___Target_Spot": "Target spot pada tomat lebih sering muncul saat curah hujan tinggi.",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Tomato Yellow Leaf Curl Virus disebarkan oleh serangga kutu kebul (whiteflies).",
    "Tomato___Tomato_mosaic_virus": "Tomato mosaic virus dapat bertahan hidup di tanah atau permukaan tanaman selama lebih dari 50 tahun.",
    "Tomato___healthy": "Tanaman tomat sehat biasanya memiliki aroma khas ketika daunnya diremas lembut."
}


for cls, fact in FUN_FACTS.items():
    pretty = cls.replace("___", " — ").replace("_", " ")
    st.markdown(f"""
    <div class='card'>
        <div class='label'>{pretty}</div>
        <div class='fact'>{fact}</div>
    </div>
    """, unsafe_allow_html=True)
