# -*- coding: utf-8 -*-
"""How_It_Works.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tt2Epr2SO2GYmN1nzDoGuVrz64vMsk20
"""

import streamlit as st

st.set_page_config(page_title="How It Works", page_icon="⚙️")

st.markdown("""
<style>
.section {
    background: #1b1f27;
    padding: 20px;
    border-radius: 14px;
    margin-bottom: 18px;
    box-shadow: 0 0 20px rgba(0,255,255,0.12);
}
.section-title {
    font-size: 24px;
    font-weight: 700;
    color: #86e1ff;
}
.section-text {
    font-size: 16px;
    color: #d4d4d4;
    margin-top: 10px;
    line-height: 1.6;
}
.flow {
    background: #11141a;
    padding: 18px;
    border-radius: 12px;
    margin-top: 10px;
    font-family: monospace;
    color: #86e1ff;
    box-shadow: 0 0 16px rgba(0,255,255,0.1);
}
</style>
""", unsafe_allow_html=True)


st.title("⚙️ How It Works")
st.write("Penjelasan lengkap bagaimana aplikasi PlantScope AI mendeteksi penyakit tanaman.")


# ===========================
#      SECTION 1 — OVERVIEW
# ===========================
st.markdown("<div class='section'>", unsafe_allow_html=True)
st.markdown("<div class='section-title'>1. Overview</div>", unsafe_allow_html=True)
st.markdown("""
<div class='section-text'>
Model yang digunakan adalah <b>DenseNet121</b> — salah satu arsitektur CNN modern yang
efisien dan sangat kuat dalam mendeteksi pola visual pada daun. Model ini dilatih pada
dataset PlantVillage/Vipooool yang berisi gambar daun dari berbagai jenis penyakit.
</div>
""", unsafe_allow_html=True)
st.markdown("</div>", unsafe_allow_html=True)

st.markdown("<div class='section'>", unsafe_allow_html=True)
st.markdown("<div class='section-title'>2. Full Pipeline (End-to-End)</div>", unsafe_allow_html=True)

st.markdown("""
<div class='flow'>
USER UPLOADS IMAGE
        ↓
Preprocessing (resize 160×160, normalize 0–1)
        ↓
DenseNet121 Feature Extraction
(121 layers, dense connectivity, deep feature maps)
        ↓
Global Average Pooling
        ↓
Fully Connected Layer
        ↓
Softmax (38 classes)
        ↓
Prediction + Confidence Score
</div>
""", unsafe_allow_html=True)

st.markdown("""
<div class='section-text'>
Pipeline ini memastikan bahwa gambar apa pun yang di-upload user akan diproses
secara konsisten sebelum masuk ke model.
</div>
""", unsafe_allow_html=True)
st.markdown("</div>", unsafe_allow_html=True)


st.markdown("<div class='section'>", unsafe_allow_html=True)
st.markdown("<div class='section-title'>3. Preprocessing</div>", unsafe_allow_html=True)
st.markdown("""
<div class='section-text'>
Sebelum masuk ke DenseNet, gambar menjalani beberapa langkah:
<ul>
    <li><b>Resize ke 160×160</b> — agar sesuai ukuran input model.</li>
    <li><b>Convert RGB</b> — memastikan 3 channel warna konsisten.</li>
    <li><b>Normalisasi (÷255)</b> — membuat nilai piksel 0–1.</li>
    <li><b>Expand dims</b> — menambah batch dimension.</li>
</ul>
Preprocessing ini penting untuk membuat input konsisten dengan data training.
</div>
""", unsafe_allow_html=True)
st.markdown("</div>", unsafe_allow_html=True)


st.markdown("<div class='section'>", unsafe_allow_html=True)
st.markdown("<div class='section-title'>4. How DenseNet121 Works</div>", unsafe_allow_html=True)

st.markdown("""
<div class='section-text'>
DenseNet121 memiliki arsitektur unik:
<ul>
    <li><b>Dense blocks</b>: setiap layer terhubung ke semua layer sebelumnya.</li>
    <li><b>Feature reuse</b>: fitur lama tidak dibuang — sangat efisien.</li>
    <li><b>Lebih ringan</b>: parameter lebih sedikit daripada ResNet/EfficientNet.</li>
    <li><b>Deep feature extraction</b>: sangat bagus untuk mendeteksi pola halus di daun.</li>
</ul>

Karena konektivitas dense ini, DenseNet mampu melihat:
✔ pola bercak halus
✔ perubahan warna tipis
✔ tekstur jamur/bakteri
✔ pola mosaik virus
</div>
""", unsafe_allow_html=True)

st.markdown("""
<div class='flow'>
[ Input Image ]
        ↓
[ Convolution ]
        ↓
[ Dense Block 1 ]──┐
        ↓          │
[ Dense Block 2 ]──┼──►  Fitur saling terhubung
        ↓          │
[ Dense Block 3 ]──┼
        ↓          │
[ Dense Block 4 ]──┘
        ↓
[ Global Average Pooling ]
        ↓
[ Fully Connected Layer ]
        ↓
[ Softmax Output ]
</div>
""", unsafe_allow_html=True)

st.markdown("</div>", unsafe_allow_html=True)


st.markdown("<div class='section'>", unsafe_allow_html=True)
st.markdown("<div class='section-title'>5. Softmax & Confidence</div>", unsafe_allow_html=True)
st.markdown("""
<div class='section-text'>
Layer terakhir adalah <b>Softmax</b> yang mengubah output model menjadi
<b>probabilitas 0–1</b> untuk 38 kelas penyakit.

Model kemudian memilih kelas dengan nilai tertinggi sebagai prediksi akhir.
</div>
""", unsafe_allow_html=True)
st.markdown("</div>", unsafe_allow_html=True)


st.markdown("<div class='section'>", unsafe_allow_html=True)
st.markdown("<div class='section-title'>6. Summary</div>", unsafe_allow_html=True)
st.markdown("""
<div class='section-text'>
PlantScope AI bekerja secara real-time dengan:
<ul>
    <li>DenseNet121 untuk feature extraction level tinggi</li>
    <li>Preprocessing agar input konsisten</li>
    <li>Softmax sebagai final classifier</li>
    <li>Confidence score yang intuitif</li>
</ul>

Hasil akhirnya: <b>deteksi penyakit daun yang akurat, cepat, dan modern.</b>
</div>
""", unsafe_allow_html=True)
st.markdown("</div>", unsafe_allow_html=True)